### ISSUE TITLE
pgbelt status breaks when tables have capitals in them

### ISSUE THREAD

**Issue by pauzed** [Autodesk/pgbelt#420]
**Describe the bug**
This is similar to https://github.com/Autodesk/pgbelt/issues/227.  belt setup still works as far as I can tell, however checking belt status returns an error locating tables that have capital letters in their name.

**To Reproduce**
1.  Create a table named using capital letters, ex: SequelizeMeta
2. Run belt setup to create pgbelt setup
3. Run belt status to check replication status
4. See error/stacktrace:

DEBUG checking source to target lag
Traceback (most recent call last):

  File "/usr/local/bin/belt", line 8, in <module>
    sys.exit(app())
             ^^^^^

  File "/usr/local/lib/python3.11/site-packages/pgbelt/cmd/helpers.py", line 105, in cmdwrapper
    run(command(dc, db, **kwargs))

  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^

  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pgbelt/cmd/helpers.py", line 58, in wrapper
    await func(

  File "/usr/local/lib/python3.11/site-packages/pgbelt/cmd/status.py", line 103, in status
    result = await gather(
             ^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pgbelt/util/postgres.py", line 492, in initialization_progress
    src_dataset_size = await get_dataset_size(tables, src_schema, src_pool, src_logger)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pgbelt/util/postgres.py", line 472, in get_dataset_size
    "db_size": await pool.fetchval(query),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/asyncpg/pool.py", line 609, in fetchval
    return await con.fetchval(
           ^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 644, in fetchval
    data = await self._execute(query, args, 1, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 1658, in _execute
    result, _ = await self.__execute(
                ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 1683, in __execute
    return await self._do_execute(
           ^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 1730, in _do_execute
    result = await executor(stmt, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "asyncpg/protocol/protocol.pyx", line 201, in bind_execute

asyncpg.exceptions.UndefinedTableError: relation "public.sequelizemeta" does not exist

**Expected behavior**
belt status properly returns replication status for tables named using capital letters

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux, OSX, Windows] OSX
 - pgbelt Version [e.g. 1.0.0] 0.7.1
 - python Version [e.g. 3.9.11] 3.11.4
 - python version(s)
 - pglogical version

**Additional context**

**Comment by pauzed** [comment]
it looks like this issue also occurs when running `belt validate-data`:

DEBUG Validating table public.SequelizeMeta...
DEBUG Validating table public.migrations...
Traceback (most recent call last):

  File "/usr/local/bin/belt", line 8, in <module>
    sys.exit(app())
             ^^^^^

  File "/usr/local/lib/python3.11/site-packages/pgbelt/cmd/helpers.py", line 105, in cmdwrapper
    run(command(dc, db, **kwargs))

  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^

  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pgbelt/cmd/helpers.py", line 58, in wrapper
    await func(

  File "/usr/local/lib/python3.11/site-packages/pgbelt/cmd/sync.py", line 173, in validate_data
    await gather(

  File "/usr/local/lib/python3.11/site-packages/pgbelt/util/postgres.py", line 202, in compare_100_rows
    await compare_data(src_pool, dst_pool, query, tables, schema, logger)

  File "/usr/local/lib/python3.11/site-packages/pgbelt/util/postgres.py", line 109, in compare_data
    src_rows = await src_pool.fetch(
               ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/asyncpg/pool.py", line 591, in fetch
    return await con.fetch(
           ^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 620, in fetch
    return await self._execute(
           ^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 1658, in _execute
    result, _ = await self.__execute(
                ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 1683, in __execute
    return await self._do_execute(
           ^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 1710, in _do_execute
    stmt = await self._get_statement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 397, in _get_statement
    statement = await self._protocol.prepare(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "asyncpg/protocol/protocol.pyx", line 168, in prepare

asyncpg.exceptions.UndefinedTableError: relation "public.sequelizemeta" does not exist
